import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#FDF8FF',
    },
    scrollViewContent: {
        paddingTop: 20,
        paddingBottom: 100,
        paddingHorizontal: 24,
        alignItems: 'center',
    },
    headerWrapper: {
        alignSelf: 'stretch',
        marginBottom: 32,
    },
    title: {
        color: '#1C1A24',
        fontSize: 32,
        fontFamily: 'Space Grotesk',
        fontWeight: '700',
        lineHeight: 40,
    },
    subtitle: {
        color: '#484555',
        fontSize: 16,
        fontFamily: 'Lexend',
        fontWeight: '400',
        lineHeight: 24,
        marginTop: 8,
    },
    searchContainer: {
        alignSelf: 'stretch',
        height: 56,
        backgroundColor: '#F1ECF9',
        borderRadius: 20,
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        marginBottom: 32,
    },
    searchIcon: {
        marginRight: 12,
    },
    searchPlaceholder: {
        color: 'rgba(121, 117, 135, 0.60)',
        fontSize: 16,
        fontFamily: 'Lexend',
    },
    filterSection: {
        alignSelf: 'stretch',
        marginBottom: 32,
    },
    filterRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 16,
        flexWrap: 'nowrap',
    },
    filterLabel: {
        color: '#4317C6',
        fontSize: 14,
        fontFamily: 'Lexend',
        fontWeight: '700',
        marginRight: 12,
    },
    activeBadge: {
        paddingHorizontal: 24,
        paddingVertical: 8,
        backgroundColor: '#4317C6',
        borderRadius: 9999,
        marginRight: 12,
        shadowColor: '#7B61FF',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.08,
        shadowRadius: 30,
        elevation: 4,
    },
    activeBadgeText: {
        color: 'white',
        fontSize: 16,
        fontFamily: 'Lexend',
        textAlign: 'center',
    },
    badge: {
        paddingHorizontal: 24,
        paddingVertical: 8,
        backgroundColor: '#F1ECF9',
        borderRadius: 9999,
        marginRight: 12,
    },
    badgeText: {
        color: '#484555',
        fontSize: 16,
        fontFamily: 'Lexend',
        textAlign: 'center',
    },
    topicList: {
        alignSelf: 'stretch',
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        gap: 16,
    },
    topicCard: {
        width: (width - 64) / 2, // Chia 2 cột
        height: 200,
        backgroundColor: 'white',
        borderRadius: 28,
        padding: 20,
        justifyContent: 'space-between',
        borderWidth: 1,
        borderColor: '#EBE6F3',
        shadowColor: '#7B61FF',
        shadowOffset: { width: 0, height: 12 },
        shadowOpacity: 0.1,
        shadowRadius: 24,
        elevation: 5,
    },
    topicIconContainer: {
        width: 56,
        height: 56,
        borderRadius: 18,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 12,
    },
    topicTitle: {
        color: '#1C1A24',
        fontSize: 20,
        fontFamily: 'Space Grotesk',
        fontWeight: '700',
        lineHeight: 26,
    },
    topicCount: {
        color: '#797587',
        fontSize: 13,
        fontFamily: 'Lexend',
        fontWeight: '500',
        marginTop: 4,
    },
    lessonList: {
        alignSelf: 'stretch',
        gap: 20,
    },
    lessonCard: {
        alignSelf: 'stretch',
        padding: 20,
        backgroundColor: 'white',
        borderRadius: 20,
        borderWidth: 1,
        borderColor: '#EBE6F3',
        shadowColor: '#7B61FF',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.08,
        shadowRadius: 30,
        elevation: 4,
    },
    lessonCardTop: {
        flexDirection: 'row',
        gap: 20,
        marginBottom: 20,
    },
    lessonImageContainer: {
        width: 96,
        height: 96,
        backgroundColor: 'rgba(91, 60, 221, 0.10)',
        borderRadius: 16,
        overflow: 'hidden',
    },
    lessonImage: {
        width: '100%',
        height: '100%',
    },
    lessonInfo: {
        flex: 1,
    },
    badgeRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 4,
    },
    levelBadge: {
        paddingHorizontal: 8,
        paddingVertical: 2,
        backgroundColor: '#E7DEFF',
        borderRadius: 6,
    },
    levelBadgeText: {
        color: '#4A3D7C',
        fontSize: 12,
        fontFamily: 'Lexend',
        fontWeight: '500',
    },
    completionText: {
        color: '#797587',
        fontSize: 12,
        fontFamily: 'Lexend',
        fontWeight: '500',
    },
    lessonTitle: {
        color: '#1C1A24',
        fontSize: 18,
        fontFamily: 'Space Grotesk',
        fontWeight: '700',
        lineHeight: 28,
        marginBottom: 4,
    },
    lessonDesc: {
        color: '#484555',
        fontSize: 12,
        fontFamily: 'Lexend',
        fontWeight: '500',
        lineHeight: 16,
    },
    cardStatsRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 16,
        marginBottom: 20,
    },
    statItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    statText: {
        color: '#484555',
        fontSize: 12,
        fontFamily: 'Lexend',
        fontWeight: '500',
    },
    progressBarBackground: {
        height: 12,
        backgroundColor: '#F1ECF9',
        borderRadius: 9999,
        marginBottom: 20,
        overflow: 'hidden',
    },
    progressBarFill: {
        height: '100%',
        borderRadius: 9999,
    },
    startButton: {
        height: 48,
        backgroundColor: '#5B3CDD',
        borderRadius: 16,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 8,
    },
    startButtonGradient: {
        // Placeholder for button gradient if supported
        backgroundColor: '#7B61FF',
    },
    startButtonText: {
        color: 'white',
        fontSize: 16,
        fontFamily: 'Lexend',
        fontWeight: '600',
    },
    startButtonTextSecondary: {
        color: '#D7CFFF',
    },
    fab: {
        position: 'absolute',
        right: 24,
        bottom: 100, // Above bottom tab bar
        width: 56,
        height: 56,
        borderRadius: 28,
        backgroundColor: '#7B61FF',
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#7B61FF',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.4,
        shadowRadius: 15,
        elevation: 8,
    },
    topNav: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 24,
        paddingVertical: 16,
        backgroundColor: 'rgba(253, 248, 255, 0.8)',
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(201, 196, 216, 0.2)',
        zIndex: 1,
    },
    logoRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    logoIcon: {
        width: 24,
        height: 24,
        backgroundColor: '#4317C6',
        borderRadius: 4,
        justifyContent: 'center',
        alignItems: 'center',
    },
    logoText: {
        color: '#4317C6',
        fontSize: 22,
        fontFamily: 'Space Grotesk',
        fontWeight: '700',
    },
    profilePic: {
        width: 40,
        height: 40,
        backgroundColor: '#EBE6F3',
        borderRadius: 20,
        borderWidth: 2,
        borderColor: 'rgba(91, 60, 221, 0.20)',
    },
    bottomTab: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        height: 73,
        paddingTop: 12,
        paddingBottom: 15,
        paddingHorizontal: 20,
        backgroundColor: 'rgba(253, 248, 255, 0.7)',
        borderTopWidth: 1,
        borderTopColor: 'rgba(201, 196, 216, 0.3)',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: 43.7,
        borderTopLeftRadius: 32,
        borderTopRightRadius: 32,
        shadowColor: '#7B61FF',
        shadowOffset: { width: 0, height: -8 },
        shadowOpacity: 0.08,
        shadowRadius: 30,
        elevation: 20,
    },
    tabItem: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 12,
    },
    activeTabItem: {
        backgroundColor: 'rgba(91, 60, 221, 0.15)',
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 16,
    },
    tabLabel: {
        fontSize: 12,
        fontFamily: 'Lexend',
        fontWeight: '500',
        marginTop: 4,
        color: '#5E5D69',
    },
    activeTabLabel: {
        color: '#4317C6',
    }
});
