import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#FDF8FF',
    },
    // Upper Header
    upperHeader: {
        height: 64,
        paddingHorizontal: 24,
        backgroundColor: '#FDF8FF',
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(201, 196, 216, 0.3)',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        zIndex: 10,
    },
    profileSection: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    profileImageWrapper: {
        width: 40,
        height: 40,
        borderRadius: 20,
        borderWidth: 2,
        borderColor: '#5B3CDD',
        overflow: 'hidden',
        justifyContent: 'center',
        alignItems: 'center',
    },
    profileImage: {
        width: 36,
        height: 36,
        borderRadius: 18,
    },
    greetingText: {
        fontSize: 12,
        fontFamily: 'Lexend',
        fontWeight: '500',
        color: '#484555',
    },
    nameText: {
        fontSize: 18,
        fontFamily: 'Space Grotesk',
        fontWeight: '700',
        color: '#4317C6',
    },
    notificationBtn: {
        width: 40,
        height: 40,
        backgroundColor: '#EBE6F3',
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
    },
    // Content
    scrollContent: {
        paddingTop: 16,
        paddingHorizontal: 24,
        paddingBottom: 150, // For bottom nav
    },
    // Banner
    bannerCard: {
        height: 180,
        padding: 20,
        backgroundColor: '#7B61FF', // Fallback
        borderRadius: 24,
        overflow: 'hidden',
        justifyContent: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.1,
        shadowRadius: 10,
        elevation: 6,
        marginBottom: 32,
    },
    bannerDecoration: {
        position: 'absolute',
        width: 150,
        height: 165,
        right: -20,
        top: 40,
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        transform: [{ rotate: '12deg' }],
    },
    bannerTag: {
        paddingHorizontal: 12,
        paddingVertical: 4,
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
        borderRadius: 9999,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        alignSelf: 'flex-start',
        marginBottom: 12,
    },
    bannerTagDot: {
        width: 8,
        height: 8,
        backgroundColor: 'white',
        borderRadius: 4,
    },
    bannerTagText: {
        color: 'white',
        fontSize: 10,
        fontFamily: 'Lexend',
        fontWeight: '700',
        letterSpacing: 0.5,
    },
    bannerTitle: {
        fontSize: 16,
        fontFamily: 'Space Grotesk',
        fontWeight: '700',
        color: 'white',
        lineHeight: 20,
        marginBottom: 4,
    },
    bannerDesc: {
        fontSize: 14,
        fontFamily: 'Lexend',
        color: '#D7CFFF',
        lineHeight: 20,
    },
    bannerBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        backgroundColor: 'white',
        paddingHorizontal: 24,
        paddingVertical: 12,
        borderRadius: 20,
        marginTop: 16,
        alignSelf: 'flex-start',
    },
    bannerBtnText: {
        color: '#4317C6',
        fontSize: 16,
        fontFamily: 'Lexend',
        fontWeight: '700',
    },
    // Quick Actions
    actionGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 12,
        marginBottom: 32,
    },
    actionCard: {
        flex: 1,
        minWidth: '45%',
        padding: 20,
        backgroundColor: 'white',
        borderRadius: 24,
        alignItems: 'center',
        gap: 8,
        borderWidth: 1,
        borderColor: '#F1ECF9',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.03,
        shadowRadius: 6,
        elevation: 2,
    },
    actionIconContainer: {
        width: 48,
        height: 48,
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
    },
    actionLabel: {
        fontSize: 16,
        fontFamily: 'Lexend',
        color: '#4317C6',
    },
    // Stats Section
    statsCard: {
        padding: 20,
        backgroundColor: 'white',
        borderRadius: 24,
        borderWidth: 1,
        borderColor: '#F1ECF9',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 32,
    },
    statsLeft: {
        gap: 12,
        flex: 1,
    },
    streakRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    streakText: {
        fontSize: 18,
        fontFamily: 'Space Grotesk',
        color: '#1C1A24',
    },
    statsQuote: {
        fontSize: 14,
        fontFamily: 'Lexend',
        color: '#484555',
        lineHeight: 20,
    },
    barChartRow: {
        flexDirection: 'row',
        alignItems: 'flex-end',
        gap: 6,
        height: 48,
        marginTop: 8,
    },
    chartBar: {
        width: 8,
        borderRadius: 4,
    },
    progressCircle: {
        width: 80,
        height: 80,
        justifyContent: 'center',
        alignItems: 'center',
        position: 'relative',
    },
    circleTrack: {
        width: 64,
        height: 64,
        borderRadius: 32,
        borderWidth: 8,
        borderColor: '#E5E0EE',
    },
    circleFill: {
        position: 'absolute',
        width: 64,
        height: 64,
        borderRadius: 32,
        borderWidth: 8,
        borderColor: '#5B3CDD',
        borderLeftColor: 'transparent',
        borderBottomColor: 'transparent',
        transform: [{ rotate: '45deg' }],
    },
    percentageText: {
        position: 'absolute',
        fontSize: 14,
        fontFamily: 'Lexend',
        fontWeight: '700',
        color: '#4317C6',
    },
    // Section Header
    sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },
    sectionTitle: {
        fontSize: 18,
        fontFamily: 'Space Grotesk',
        color: '#1C1A24',
    },
    viewAllBtn: {
        fontSize: 14,
        fontFamily: 'Lexend',
        fontWeight: '700',
        color: '#4317C6',
    },
    // History
    historyList: {
        gap: 12,
        marginBottom: 32,
    },
    historyItem: {
        padding: 12,
        backgroundColor: 'white',
        borderRadius: 20,
        borderWidth: 1,
        borderColor: '#F1ECF9',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    historyLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    historyIconBox: {
        width: 40,
        height: 40,
        backgroundColor: '#F1ECF9',
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
    },
    historyTitle: {
        fontSize: 16,
        fontFamily: 'Lexend',
        color: '#1C1A24',
    },
    historyTime: {
        fontSize: 10,
        fontFamily: 'Lexend',
        color: '#484555',
    },
    historyScanBtn: {
        width: 32,
        height: 32,
        backgroundColor: 'rgba(201, 191, 255, 0.2)',
        borderRadius: 8,
        justifyContent: 'center',
        alignItems: 'center',
    },
    // Lessons Horizontal
    lessonScroll: {
        marginHorizontal: -24,
        paddingHorizontal: 24,
    },
    lessonCard: {
        width: 200,
        marginRight: 16,
        backgroundColor: 'white',
        borderRadius: 24,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: '#F1ECF9',
    },
    lessonImageContainer: {
        height: 112,
        position: 'relative',
    },
    lessonImage: {
        width: '100%',
        height: '100%',
    },
    lessonDifficulty: {
        position: 'absolute',
        left: 8,
        bottom: 8,
        backgroundColor: '#4317C6',
        borderRadius: 9999,
        paddingHorizontal: 8,
        paddingVertical: 2,
    },
    lessonDifficultyText: {
        color: 'white',
        fontSize: 10,
        fontFamily: 'Lexend',
        fontWeight: '700',
    },
    lessonInfo: {
        padding: 12,
    },
    lessonItemTitle: {
        fontSize: 14,
        fontFamily: 'Lexend',
        fontWeight: '700',
        color: '#1C1A24',
        marginBottom: 4,
    },
    lessonItemMeta: {
        fontSize: 11,
        fontFamily: 'Lexend',
        color: '#484555',
    },
    // Bottom Nav
    bottomNav: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        height: 80,
        paddingHorizontal: 20,
        paddingTop: 12,
        paddingBottom: 20,
        backgroundColor: 'rgba(253, 248, 255, 0.8)',
        borderTopWidth: 1,
        borderTopColor: 'rgba(201, 196, 216, 0.3)',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    navItem: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 12,
    },
    navItemActive: {
        backgroundColor: '#5B3CDD',
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 12,
    },
    navText: {
        fontSize: 12,
        fontFamily: 'Lexend',
        fontWeight: '500',
        color: '#5E5D69',
        marginTop: 4,
    },
    navTextActive: {
        color: '#D7CFFF',
        fontSize: 10,
        marginTop: 4,
    },
    fabContainer: {
        position: 'absolute',
        bottom: 100,
        right: 24,
        width: 64,
        height: 64,
        borderRadius: 32,
        backgroundColor: '#7B61FF',
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#7B61FF',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.3,
        shadowRadius: 10,
        elevation: 8,
    }
});
