import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#FDF8FF',
    },
    scrollViewContent: {
        paddingTop: 80,
        paddingBottom: 128,
        paddingHorizontal: 24,
    },
    videoCard: {
        alignSelf: 'stretch',
        backgroundColor: '#1A1A1A',
        borderRadius: 32,
        overflow: 'hidden',
        shadowColor: '#7B61FF',
        shadowOffset: { width: 0, height: 20 },
        shadowOpacity: 0.15,
        shadowRadius: 50,
        elevation: 10,
        marginBottom: 32,
    },
    videoPlaceholder: {
        width: '100%',
        height: 192,
        opacity: 0.9,
    },
    videoControlsOverlay: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        padding: 20,
        backgroundColor: 'rgba(0, 0, 0, 0.4)',
    },
    videoTopControls: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
    },
    controlGroupLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 20,
    },
    controlGroupRight: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 20,
    },
    speedBadge: {
        paddingHorizontal: 12,
        paddingVertical: 4,
        backgroundColor: 'rgba(255, 255, 255, 0.20)',
        borderRadius: 9999,
    },
    speedText: {
        color: 'white',
        fontSize: 12,
        fontFamily: 'Lexend',
        fontWeight: '500',
    },
    progressBarContainer: {
        alignSelf: 'stretch',
        height: 6,
        backgroundColor: 'rgba(255, 255, 255, 0.30)',
        borderRadius: 9999,
        overflow: 'hidden',
    },
    progressBarFill: {
        height: '100%',
        width: '30%', // Simulated progress
        backgroundColor: '#7B61FF',
        borderRadius: 9999,
    },
    playButtonCenter: {
        position: 'absolute',
        top: '50%',
        left: '50%',
        marginTop: -32,
        marginLeft: -32,
        width: 64,
        height: 64,
        backgroundColor: 'rgba(255, 255, 255, 0.70)',
        borderRadius: 32,
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 10,
    },
    lessonInfoSection: {
        alignSelf: 'stretch',
        marginBottom: 32,
    },
    lessonTitle: {
        color: '#1C1A24',
        fontSize: 32,
        fontFamily: 'Space Grotesk',
        fontWeight: '600',
        lineHeight: 40,
        marginBottom: 8,
    },
    lessonDescription: {
        color: '#484555',
        fontSize: 16,
        fontFamily: 'Lexend',
        fontWeight: '400',
        lineHeight: 26,
        marginBottom: 12,
    },
    tagRow: {
        flexDirection: 'row',
        gap: 12,
    },
    tagBadge: {
        paddingHorizontal: 16,
        paddingVertical: 8,
        backgroundColor: '#F1ECF9',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: 'rgba(67, 23, 198, 0.10)',
    },
    tagText: {
        color: '#4317C6',
        fontSize: 14,
        fontFamily: 'Lexend',
        fontWeight: '400',
    },
    vocabularySection: {
        alignSelf: 'stretch',
        marginBottom: 32,
    },
    sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    sectionTitle: {
        color: '#1C1A24',
        fontSize: 24,
        fontFamily: 'Space Grotesk',
        fontWeight: '600',
    },
    sectionCount: {
        color: '#4317C6',
        fontSize: 16,
        fontFamily: 'Lexend',
    },
    vocabList: {
        gap: 12,
    },
    vocabItem: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 20,
        backgroundColor: '#F7F1FF',
        borderRadius: 20,
        borderWidth: 1,
        borderColor: 'rgba(201, 196, 216, 0.30)',
        gap: 20,
    },
    vocabIconContainer: {
        width: 48,
        height: 48,
        backgroundColor: 'rgba(67, 23, 198, 0.10)',
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
    },
    vocabInfo: {
        flex: 1,
    },
    vocabName: {
        color: '#1C1A24',
        fontSize: 16,
        fontFamily: 'Lexend',
        fontWeight: '500',
    },
    vocabUppercase: {
        color: '#484555',
        fontSize: 10,
        fontFamily: 'Lexend',
        fontWeight: '400',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
        marginTop: 2,
    },
    actionSectionContainer: {
        alignSelf: 'stretch',
        paddingBottom: 32,
        gap: 16,
    },
    btnPracticeNow: {
        alignSelf: 'stretch',
        height: 56,
        borderRadius: 16,
        overflow: 'hidden',
        shadowColor: '#7B61FF',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.3,
        shadowRadius: 30,
        elevation: 8,
    },
    btnGradient: {
        flex: 1,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 12,
    },
    btnTextWhite: {
        color: 'white',
        fontSize: 18,
        fontFamily: 'Lexend',
        fontWeight: '400',
    },
    secondaryButtonRow: {
        flexDirection: 'row',
        gap: 12,
    },
    btnTakeQuiz: {
        flex: 1,
        height: 56,
        backgroundColor: '#EBE6F3',
        borderRadius: 16,
        borderWidth: 1,
        borderColor: 'rgba(67, 23, 198, 0.10)',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 12,
    },
    btnDictionary: {
        flex: 1,
        height: 56,
        backgroundColor: '#F7F1FF',
        borderRadius: 16,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 12,
    },
    btnTextPurple: {
        color: '#4317C6',
        fontSize: 16,
        fontFamily: 'Lexend',
        fontWeight: '400',
    },
    btnTextGray: {
        color: '#5E5D69',
        fontSize: 16,
        fontFamily: 'Lexend',
        fontWeight: '400',
    },
    headerNav: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        height: 80,
        paddingTop: 30,
        paddingHorizontal: 24,
        backgroundColor: 'rgba(253, 248, 255, 0.70)',
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(201, 196, 216, 0.30)',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        zIndex: 100,
    },
    headerLogoText: {
        color: '#4317C6',
        fontSize: 24,
        fontFamily: 'Space Grotesk',
        fontWeight: '700',
    },
    headerProfilePic: {
        width: 40,
        height: 40,
        borderRadius: 20,
        borderWidth: 2,
        borderColor: 'rgba(91, 60, 221, 0.20)',
    },
    bottomNav: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        height: 80,
        paddingBottom: 24,
        paddingTop: 12,
        paddingHorizontal: 24,
        backgroundColor: 'rgba(253, 248, 255, 0.70)',
        borderTopWidth: 1,
        borderTopColor: 'rgba(201, 196, 216, 0.30)',
        borderTopLeftRadius: 32,
        borderTopRightRadius: 32,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: 43.7,
        zIndex: 100,
    },
    navItemTab: {
        alignItems: 'center',
        justifyContent: 'center',
        flex: 1,
    },
    navItemActive: {
        backgroundColor: 'rgba(91, 60, 221, 0.20)',
        borderRadius: 12,
        paddingVertical: 4,
        paddingHorizontal: 16,
    },
    navItemText: {
        fontSize: 12,
        fontFamily: 'Lexend',
        fontWeight: '500',
        color: '#5E5D69',
        marginTop: 4,
    },
    navItemTextActive: {
        color: '#4317C6',
    }
});
