import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#FDF8FF',
    },
    header: {
        height: 64,
        paddingHorizontal: 24,
        paddingTop: 40,
        justifyContent: 'center',
        backgroundColor: 'transparent',
    },
    logoText: {
        color: '#4317C6',
        fontSize: 24,
        fontFamily: 'Space Grotesk',
        fontWeight: '700',
    },
    content: {
        flex: 1,
        justifyContent: 'center',
        paddingHorizontal: 24,
    },
    blurCircle1: {
        position: 'absolute',
        width: 232,
        height: 232,
        right: -80,
        top: -40,
        backgroundColor: 'rgba(116, 89, 247, 0.15)',
        borderRadius: 116,
    },
    blurCircle2: {
        position: 'absolute',
        width: 200,
        height: 200,
        left: -60,
        bottom: 80,
        backgroundColor: 'rgba(95, 82, 147, 0.15)',
        borderRadius: 100,
    },
    card: {
        width: '100%',
        padding: 32,
        backgroundColor: 'rgba(253, 248, 255, 0.75)',
        borderRadius: 32,
        borderWidth: 1,
        borderColor: 'rgba(201, 196, 216, 0.4)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.05,
        shadowRadius: 20,
        elevation: 10,
    },
    title: {
        fontSize: 32,
        fontFamily: 'Space Grotesk',
        fontWeight: '700',
        color: '#1C1A24',
        marginBottom: 8,
        lineHeight: 40,
    },
    subtitle: {
        fontSize: 14,
        fontFamily: 'Lexend',
        color: '#484555',
        lineHeight: 22,
        marginBottom: 32,
    },
    inputGroup: {
        marginBottom: 20,
        alignSelf: 'stretch',
    },
    labelRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 8,
    },
    label: {
        fontSize: 14,
        fontFamily: 'Lexend',
        fontWeight: '600',
        color: '#484555',
    },
    forgotText: {
        fontSize: 14,
        fontFamily: 'Lexend',
        fontWeight: '600',
        color: '#4317C6',
    },
    inputWrapper: {
        height: 54,
        backgroundColor: '#F7F1FF',
        borderRadius: 14,
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        borderWidth: 1,
        borderColor: '#C9C4D8',
    },
    inputIcon: {
        marginRight: 12,
    },
    input: {
        flex: 1,
        fontSize: 16,
        fontFamily: 'Lexend',
        color: '#1C1A24',
    },
    signInButton: {
        height: 56,
        backgroundColor: '#4317C6',
        borderRadius: 28,
        justifyContent: 'center',
        alignItems: 'center',
        flexDirection: 'row',
        marginTop: 12,
        shadowColor: '#4317C6',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.3,
        shadowRadius: 15,
        elevation: 8,
    },
    signInText: {
        color: 'white',
        fontSize: 16,
        fontFamily: 'Lexend',
        fontWeight: '600',
        marginRight: 8,
    },
    dividerContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginVertical: 28,
    },
    dividerLine: {
        flex: 1,
        height: 1,
        backgroundColor: '#D9D5E4',
    },
    dividerText: {
        paddingHorizontal: 16,
        fontSize: 11,
        fontFamily: 'Lexend',
        fontWeight: '600',
        color: '#797587',
        textTransform: 'uppercase',
    },
    socialRow: {
        flexDirection: 'row',
        gap: 12,
    },
    socialButton: {
        flex: 1,
        height: 52,
        backgroundColor: '#FDF8FF',
        borderRadius: 14,
        borderWidth: 1,
        borderColor: '#C9C4D8',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 8,
    },
    socialText: {
        fontSize: 14,
        fontFamily: 'Lexend',
        fontWeight: '600',
        color: '#484555',
    },
    footer: {
        flexDirection: 'row',
        justifyContent: 'center',
        marginTop: 32,
    },
    footerText: {
        fontSize: 14,
        fontFamily: 'Lexend',
        color: '#484555',
    },
    footerLink: {
        fontSize: 14,
        fontFamily: 'Lexend',
        fontWeight: '600',
        color: '#4317C6',
    }
});
