import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#FDF8FF',
    },
    scrollViewContent: {
        paddingTop: 96,
        paddingBottom: 180,
    },
    // Visual Section (Viewfinder)
    videoContainer: {
        paddingHorizontal: 24,
        marginBottom: 16,
    },
    videoWrapper: {
        alignSelf: 'stretch',
        backgroundColor: '#F1ECF9',
        borderRadius: 32,
        overflow: 'hidden',
        borderWidth: 2,
        borderColor: '#EBE6F3',
        position: 'relative',
        height: 188.38,
    },
    videoPlaceholder: {
        width: '100%',
        height: 188.38,
    },
    markerContainer: {
        position: 'absolute',
        left: 18,
        top: 18,
        right: 18,
        bottom: 18,
    },
    markerBase: {
        position: 'absolute',
        width: 32,
        height: 32,
        opacity: 0.8,
        borderColor: '#7B61FF',
    },
    markerTopLeft: {
        left: 0,
        top: 0,
        borderTopWidth: 4,
        borderLeftWidth: 4,
        borderTopLeftRadius: 12,
    },
    markerTopRight: {
        right: 0,
        top: 0,
        borderTopWidth: 4,
        borderRightWidth: 4,
        borderTopRightRadius: 12,
    },
    markerBottomLeft: {
        left: 0,
        bottom: 0,
        borderBottomWidth: 4,
        borderLeftWidth: 4,
        borderBottomLeftRadius: 12,
    },
    markerBottomRight: {
        right: 0,
        bottom: 0,
        borderBottomWidth: 4,
        borderRightWidth: 4,
        borderBottomRightRadius: 12,
    },
    playButtonOverlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: 'rgba(0,0,0,0.1)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    playButtonCircle: {
        width: 80,
        height: 80,
        borderRadius: 40,
        backgroundColor: '#7B61FF',
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#4317C6',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.2,
        shadowRadius: 15,
        elevation: 8,
    },
    // Media Control Bar
    controlBar: {
        marginHorizontal: 24,
        flexDirection: 'row',
        alignItems: 'center',
        padding: 16,
        backgroundColor: 'rgba(253, 248, 255, 0.7)',
        borderRadius: 16,
        borderWidth: 1,
        borderColor: 'rgba(201, 196, 216, 0.3)',
        gap: 16,
    },
    controlItem: {
        alignItems: 'center',
        gap: 4,
    },
    controlText: {
        color: '#484555',
        fontSize: 12,
        fontFamily: 'Lexend',
        fontWeight: '500',
    },
    trackWrapper: {
        flex: 1,
        height: 12,
        backgroundColor: '#EBE6F3',
        borderRadius: 9999,
        overflow: 'hidden',
    },
    trackFill: {
        width: '38%',
        height: '100%',
        backgroundColor: '#7B61FF',
        borderRadius: 9999,
    },
    timerText: {
        color: '#484555',
        fontSize: 12,
        fontFamily: 'Lexend',
        fontWeight: '500',
    },
    // Content Section
    contentSection: {
        paddingHorizontal: 24,
        marginTop: 16,
    },
    howToTitle: {
        fontSize: 24,
        fontFamily: 'Space Grotesk',
        fontWeight: '600',
        color: '#1C1A24',
        marginBottom: 16,
        paddingLeft: 4,
    },
    stepList: {
        gap: 12,
    },
    stepCard: {
        padding: 20,
        backgroundColor: '#F7F1FF',
        borderRadius: 20,
        borderWidth: 1,
        borderColor: '#EBE6F3',
        flexDirection: 'row',
        gap: 16,
    },
    stepCircle: {
        width: 40,
        height: 40,
        backgroundColor: 'rgba(91, 60, 221, 0.2)',
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
    },
    stepNumber: {
        color: '#4317C6',
        fontSize: 16,
        fontFamily: 'Lexend',
        fontWeight: '700',
    },
    stepRight: {
        flex: 1,
        gap: 12,
    },
    stepText: {
        fontSize: 16,
        fontFamily: 'Lexend',
        color: '#1C1A24',
        lineHeight: 24,
    },
    stepLabelRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    stepLabelText: {
        fontSize: 12,
        fontFamily: 'Lexend',
        fontWeight: '500',
        color: '#4317C6',
    },
    // Header Overlay
    headerOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        height: 64,
        paddingHorizontal: 24,
        backgroundColor: 'rgba(253, 248, 255, 0.7)',
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(201, 196, 216, 0.3)',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        zIndex: 10,
    },
    headerLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 16,
    },
    backIconContainer: {
        width: 32,
        height: 32,
        borderRadius: 16,
        justifyContent: 'center',
        alignItems: 'center',
    },
    headerTitleText: {
        fontSize: 24,
        fontFamily: 'Space Grotesk',
        fontWeight: '700',
        color: '#4317C6',
    },
    headerProfile: {
        width: 40,
        height: 40,
        borderRadius: 20,
        borderWidth: 2,
        borderColor: 'rgba(67, 23, 198, 0.2)',
        overflow: 'hidden',
    },
    // Footer Overlay
    footerOverlay: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        paddingTop: 16,
        paddingBottom: 32,
        paddingHorizontal: 24,
        backgroundColor: 'rgba(253, 248, 255, 0.7)',
        borderTopWidth: 1,
        borderTopColor: 'rgba(201, 196, 216, 0.3)',
        gap: 16,
        zIndex: 10,
    },
    footerNavRow: {
        flexDirection: 'row',
        gap: 16,
    },
    navBtn: {
        flex: 1,
        height: 56,
        backgroundColor: '#EBE6F3',
        borderRadius: 16,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 8,
    },
    navBtnText: {
        fontSize: 16,
        fontFamily: 'Lexend',
        color: '#484555',
        fontWeight: '400',
    },
    actionBtn: {
        height: 56,
        backgroundColor: '#7B61FF',
        borderRadius: 16,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 8,
        shadowColor: 'rgba(67, 23, 198, 0.2)',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 1,
        shadowRadius: 15,
        elevation: 8,
    },
    actionBtnText: {
        fontSize: 18,
        fontFamily: 'Lexend',
        fontWeight: '700',
        color: 'white',
    }
});
