import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#FDF8FF',
    },
    scrollContent: {
        paddingBottom: 100,
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 24,
        paddingTop: 10,
        height: 64,
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(201, 196, 216, 0.3)',
    },
    logoContainer: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    logoIcon: {
        width: 36,
        height: 36,
        borderRadius: 18,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 8,
        borderWidth: 2,
        borderColor: '#7B61FF',
        overflow: 'hidden',
    },
    logoText: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#4317C6',
        fontFamily: 'Space Grotesk',
    },
    settingsBtn: {
        padding: 5,
    },
    mainContent: {
        paddingHorizontal: 24,
        paddingTop: 20,
    },
    profileCard: {
        backgroundColor: 'rgba(241, 236, 249, 0.6)',
        borderRadius: 24,
        paddingVertical: 30,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#F1ECF9',
        marginBottom: 24,
    },
    avatarWrapper: {
        position: 'relative',
        marginBottom: 16,
    },
    avatarGradient: {
        padding: 4,
        borderRadius: 100,
    },
    avatarBorder: {
        padding: 4,
        backgroundColor: '#FDF8FF',
        borderRadius: 100,
    },
    avatar: {
        width: 80,
        height: 80,
        borderRadius: 40,
    },
    editAvatarBtn: {
        position: 'absolute',
        bottom: 0,
        right: 0,
        width: 28,
        height: 28,
        borderRadius: 14,
        justifyContent: 'center',
        alignItems: 'center',
        elevation: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
    },
    userName: {
        fontSize: 32,
        fontWeight: 'bold',
        color: '#1C1A24',
        fontFamily: 'Space Grotesk',
        textAlign: 'center',
    },
    userSubtitle: {
        fontSize: 16,
        color: '#484555',
        textAlign: 'center',
        marginTop: 4,
        marginBottom: 20,
        fontFamily: 'Lexend',
    },
    badgesRow: {
        flexDirection: 'row',
        gap: 12,
    },
    verifiedBadge: {
        backgroundColor: '#5B3CDD',
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 6,
        paddingHorizontal: 12,
        borderRadius: 20,
        gap: 4,
    },
    verifiedText: {
        color: '#D7CFFF',
        fontSize: 12,
        fontWeight: '500',
    },
    streakBadge: {
        backgroundColor: '#E1DEEC',
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 6,
        paddingHorizontal: 12,
        borderRadius: 20,
        gap: 4,
    },
    streakText: {
        color: '#62616D',
        fontSize: 12,
        fontWeight: '500',
    },
    // Progress Card
    progressCard: {
        backgroundColor: 'rgba(241, 236, 249, 0.6)',
        borderRadius: 24,
        padding: 20,
        borderWidth: 1,
        borderColor: '#F1ECF9',
        marginBottom: 24,
    },
    progressHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
    },
    progressTitle: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#1C1A24',
        fontFamily: 'Space Grotesk',
    },
    levelBadge: {
        fontSize: 14,
        fontWeight: '600',
        color: '#4317C6',
        fontFamily: 'Lexend',
    },
    xpRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 8,
    },
    xpLabel: {
        fontSize: 16,
        color: '#484555',
        fontFamily: 'Lexend',
    },
    xpValue: {
        fontSize: 16,
        color: '#484555',
        fontWeight: '500',
        fontFamily: 'Lexend',
    },
    progressBarBg: {
        height: 12,
        backgroundColor: '#F1ECF9',
        borderRadius: 6,
        overflow: 'hidden',
        marginBottom: 20,
    },
    progressBarFill: {
        height: '100%',
        borderRadius: 6,
    },
    statsGrid: {
        flexDirection: 'row',
        gap: 12,
    },
    statBox: {
        flex: 1,
        backgroundColor: '#FDF8FF',
        borderRadius: 16,
        padding: 12,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: 'rgba(201, 196, 216, 0.3)',
    },
    statBoxLabel: {
        fontSize: 14,
        color: '#484555',
        textAlign: 'center',
        marginBottom: 4,
        fontFamily: 'Lexend',
    },
    statBoxValue: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#4317C6',
        fontFamily: 'Space Grotesk',
    },
    // Achievements
    sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
    },
    sectionTitle: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#1C1A24',
        fontFamily: 'Space Grotesk',
    },
    seeAllBtn: {
        fontSize: 14,
        fontWeight: '600',
        color: '#4317C6',
        fontFamily: 'Lexend',
    },
    achievementsGrid: {
        flexDirection: 'row',
        gap: 12,
        marginBottom: 24,
    },
    achievementCard: {
        flex: 1,
        backgroundColor: 'rgba(241, 236, 249, 0.6)',
        borderRadius: 16,
        padding: 12,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#F1ECF9',
    },
    achievementCardLocked: {
        opacity: 0.5,
        backgroundColor: '#FFFFFF',
    },
    achievementIconBox: {
        width: 48,
        height: 48,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 8,
    },
    achievementName: {
        fontSize: 12,
        fontWeight: '500',
        color: '#1C1A24',
        textAlign: 'center',
        fontFamily: 'Lexend',
    },
    // Settings List
    settingsCard: {
        backgroundColor: 'rgba(241, 236, 249, 0.6)',
        borderRadius: 24,
        borderWidth: 1,
        borderColor: '#F1ECF9',
        overflow: 'hidden',
    },
    settingsGroupHeader: {
        paddingHorizontal: 20,
        paddingVertical: 12,
        backgroundColor: 'rgba(247, 241, 255, 0.5)',
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(201, 196, 216, 0.3)',
    },
    settingsGroupTitle: {
        fontSize: 14,
        fontWeight: '600',
        color: '#484555',
        fontFamily: 'Lexend',
    },
    settingItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingVertical: 20,
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(201, 196, 216, 0.3)',
    },
    settingItemLast: {
        borderBottomWidth: 0,
    },
    settingLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 16,
    },
    settingText: {
        fontSize: 16,
        color: '#1C1A24',
        fontFamily: 'Lexend',
    },
    settingRight: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    settingValue: {
        fontSize: 16,
        color: '#484555',
        fontFamily: 'Lexend',
    },
    logoutText: {
        color: '#BA1A1A',
        fontWeight: '500',
    },
    fab: {
        position: 'absolute',
        right: 24,
        bottom: 80,
        width: 56,
        height: 56,
        borderRadius: 28,
        elevation: 8,
        shadowColor: '#7B61FF',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 10,
        zIndex: 10,
    },
    fabGradient: {
        width: '100%',
        height: '100%',
        borderRadius: 28,
        justifyContent: 'center',
        alignItems: 'center',
    },
});

export default styles;
