import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#FDF8FF',
    },
    scrollViewContent: {
        paddingTop: 80,
        paddingBottom: 150,
        paddingHorizontal: 24,
    },
    xpCard: {
        alignSelf: 'stretch',
        padding: 32,
        borderRadius: 32,
        alignItems: 'center',
        marginBottom: 24,
        shadowColor: '#7B61FF',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.2,
        shadowRadius: 30,
        elevation: 8,
    },
    xpIconContainer: {
        width: 80,
        height: 80,
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
        borderRadius: 40,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 16,
    },
    xpLabel: {
        color: 'white',
        fontSize: 16,
        fontFamily: 'Lexend',
        opacity: 0.9,
    },
    xpValue: {
        color: 'white',
        fontSize: 32,
        fontFamily: 'Space Grotesk',
        fontWeight: '600',
    },
    xpProgressBackground: {
        alignSelf: 'stretch',
        height: 12,
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
        borderRadius: 9999,
        marginTop: 24,
        overflow: 'hidden',
    },
    xpProgressBar: {
        height: '100%',
        backgroundColor: 'white',
        borderRadius: 9999,
    },
    xpGoalText: {
        color: 'white',
        fontSize: 14,
        fontFamily: 'Lexend',
        opacity: 0.8,
        marginTop: 8,
    },
    resultSummaryCard: {
        alignSelf: 'stretch',
        padding: 32,
        backgroundColor: '#F1ECF9',
        borderRadius: 32,
        borderWidth: 1,
        borderColor: 'rgba(201, 196, 216, 0.2)',
        marginBottom: 32,
    },
    categoryTag: {
        color: '#4317C6',
        fontSize: 14,
        fontFamily: 'Lexend',
        textTransform: 'uppercase',
        letterSpacing: 1.6,
        marginBottom: 8,
    },
    congratsTitle: {
        color: '#1C1A24',
        fontSize: 40,
        fontFamily: 'Space Grotesk',
        fontWeight: '700',
        lineHeight: 48,
        marginBottom: 8,
    },
    congratsSub: {
        color: '#484555',
        fontSize: 16,
        fontFamily: 'Lexend',
        lineHeight: 24,
        marginBottom: 32,
    },
    scoreRow: {
        flexDirection: 'row',
        alignItems: 'flex-end',
        gap: 8,
    },
    scoreMain: {
        color: '#4317C6',
        fontSize: 64,
        fontFamily: 'Space Grotesk',
        lineHeight: 64,
    },
    scoreSub: {
        color: '#797587',
        fontSize: 24,
        fontFamily: 'Lexend',
        fontWeight: '600',
        paddingBottom: 8,
    },
    sectionTitleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginBottom: 16,
    },
    sectionTitle: {
        color: '#1C1A24',
        fontSize: 24,
        fontFamily: 'Space Grotesk',
        fontWeight: '600',
    },
    questionDetailCard: {
        alignSelf: 'stretch',
        padding: 24,
        backgroundColor: 'white',
        borderRadius: 24,
        borderWidth: 1,
        borderColor: 'rgba(201, 196, 216, 0.3)',
        marginBottom: 16,
        position: 'relative',
        overflow: 'hidden',
    },
    wrongIndicator: {
        position: 'absolute',
        top: 0,
        left: 0,
        width: 4,
        height: '100%',
        backgroundColor: '#BA1A1A',
    },
    correctIndicator: {
        position: 'absolute',
        top: 0,
        left: 0,
        width: 4,
        height: '100%',
        backgroundColor: '#16A34A',
    },
    qHeader: {
        flexDirection: 'row',
        gap: 16,
    },
    statusIcon: {
        width: 32,
        height: 32,
        borderRadius: 16,
        justifyContent: 'center',
        alignItems: 'center',
    },
    qContent: {
        flex: 1,
    },
    qNum: {
        color: '#484555',
        fontSize: 14,
        fontFamily: 'Lexend',
        marginBottom: 4,
    },
    qTitle: {
        color: '#1C1A24',
        fontSize: 20,
        fontFamily: 'Space Grotesk',
        fontWeight: '600',
        marginBottom: 16,
    },
    choiceRow: {
        padding: 12,
        borderRadius: 12,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginBottom: 8,
    },
    userChoiceBg: {
        backgroundColor: '#F1ECF9',
        borderWidth: 1,
        borderColor: 'rgba(201, 196, 216, 0.5)',
    },
    userChoiceWrongBg: {
        backgroundColor: 'rgba(255, 218, 214, 0.2)',
        borderColor: 'rgba(186, 26, 26, 0.3)',
    },
    correctChoiceBg: {
        backgroundColor: '#F0FDF4',
        borderWidth: 1,
        borderColor: '#BBF7D0',
    },
    choiceLabel: {
        fontSize: 14,
        fontFamily: 'Lexend',
        color: '#797587',
    },
    userChoiceText: {
        fontSize: 16,
        fontFamily: 'Lexend',
        color: '#1C1A24',
    },
    userChoiceWrongText: {
        color: '#BA1A1A',
    },
    correctChoiceLabel: {
        color: '#15803D',
    },
    correctChoiceText: {
        color: '#166534',
        fontWeight: '600',
    },
    watchAgainBtn: {
        height: 48,
        backgroundColor: '#E5DEFF',
        borderRadius: 9999,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 8,
        marginTop: 12,
    },
    watchAgainText: {
        color: '#451CC8',
        fontSize: 16,
        fontFamily: 'Lexend',
    },
    relearnBtn: {
        height: 48,
        borderRadius: 9999,
        overflow: 'hidden',
        marginTop: 12,
    },
    relearnGradient: {
        flex: 1,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 8,
    },
    relearnText: {
        color: 'white',
        fontSize: 16,
        fontFamily: 'Lexend',
    },
    footerActions: {
        paddingTop: 16,
        gap: 16,
    },
    backBtn: {
        height: 56,
        backgroundColor: '#EBE6F3',
        borderRadius: 16,
        borderWidth: 1,
        borderColor: 'rgba(201, 196, 216, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
        flexDirection: 'row',
        gap: 8,
    },
    backText: {
        color: '#4317C6',
        fontSize: 16,
        fontFamily: 'Lexend',
    },
    continueBtn: {
        height: 56,
        borderRadius: 16,
        overflow: 'hidden',
        shadowColor: '#7B61FF',
        shadowOffset: { width: 0, height: 15 },
        shadowOpacity: 0.25,
        shadowRadius: 30,
        elevation: 10,
    },
    continueGradient: {
        flex: 1,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 8,
    },
    continueText: {
        color: 'white',
        fontSize: 16,
        fontFamily: 'Lexend',
    },
    topNav: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        height: 80,
        paddingTop: 30,
        paddingHorizontal: 24,
        backgroundColor: 'rgba(253, 248, 255, 0.7)',
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(201, 196, 216, 0.3)',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        zIndex: 10,
    },
    headerTitle: {
        color: '#4317C6',
        fontSize: 24,
        fontFamily: 'Space Grotesk',
        fontWeight: '700',
    },
    avatar: {
        width: 40,
        height: 40,
        borderRadius: 20,
        borderWidth: 2,
        borderColor: 'rgba(91, 60, 221, 0.2)',
    }
});
