import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#FDF8FF',
    },
    scrollViewContent: {
        paddingTop: 80,
        paddingBottom: 150,
        paddingHorizontal: 24,
    },
    headerWrapper: {
        alignSelf: 'stretch',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-end',
        marginBottom: 12,
    },
    questionProgressText: {
        color: '#4317C6',
        fontSize: 16,
        fontFamily: 'Lexend',
        fontWeight: '400',
        textTransform: 'uppercase',
        lineHeight: 24,
        letterSpacing: 0.8,
    },
    categoryText: {
        color: '#5E5D69',
        fontSize: 16,
        fontFamily: 'Lexend',
        fontWeight: '400',
        lineHeight: 24,
        textAlign: 'right',
    },
    progressBarBackground: {
        alignSelf: 'stretch',
        height: 12,
        backgroundColor: '#F1ECF9',
        borderRadius: 9999,
        marginBottom: 24,
        overflow: 'hidden',
    },
    progressBarFill: {
        height: '100%',
        borderRadius: 9999,
    },
    questionText: {
        color: '#1C1A24',
        fontSize: 32,
        fontFamily: 'Space Grotesk',
        fontWeight: '600',
        lineHeight: 40,
        marginBottom: 24,
    },
    videoCard: {
        alignSelf: 'stretch',
        backgroundColor: '#1A1A1A',
        borderRadius: 24,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: 'rgba(201, 196, 216, 0.2)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 25 },
        shadowOpacity: 0.25,
        shadowRadius: 50,
        elevation: 10,
        marginBottom: 24,
    },
    videoPlaceholder: {
        width: '100%',
        height: 190,
    },
    markerContainer: {
        ...StyleSheet.absoluteFillObject,
        padding: 16,
    },
    markerBase: {
        position: 'absolute',
        width: 32,
        height: 32,
        borderColor: '#A78BFA',
        opacity: 0.6,
    },
    markerTopLeft: {
        top: 16,
        left: 16,
        borderTopWidth: 2,
        borderLeftWidth: 2,
    },
    markerTopRight: {
        top: 16,
        right: 16,
        borderTopWidth: 2,
        borderRightWidth: 2,
    },
    markerBottomLeft: {
        bottom: 16,
        left: 16,
        borderBottomWidth: 2,
        borderLeftWidth: 2,
    },
    markerBottomRight: {
        bottom: 16,
        right: 16,
        borderBottomWidth: 2,
        borderRightWidth: 2,
    },
    replayButton: {
        position: 'absolute',
        right: 16,
        bottom: 16,
        paddingHorizontal: 16,
        paddingVertical: 12,
        backgroundColor: 'rgba(253, 248, 255, 0.8)',
        borderRadius: 16,
        borderWidth: 1,
        borderColor: 'rgba(201, 196, 216, 0.3)',
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        backdropFilter: 'blur(6px)',
    },
    replayText: {
        color: '#1C1A24',
        fontSize: 16,
        fontFamily: 'Lexend',
        fontWeight: '400',
    },
    optionsContainer: {
        alignSelf: 'stretch',
        gap: 12,
    },
    optionCard: {
        padding: 20,
        backgroundColor: '#FDF8FF',
        borderRadius: 20,
        borderWidth: 2,
        borderColor: '#EBE6F3',
        flexDirection: 'row',
        alignItems: 'center',
    },
    optionCardActive: {
        backgroundColor: 'rgba(91, 60, 221, 0.05)',
        borderColor: '#4317C6',
    },
    optionLetterBox: {
        width: 48,
        height: 48,
        backgroundColor: '#EBE6F3',
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
    },
    optionLetterBoxActive: {
        backgroundColor: '#5B3CDD',
    },
    optionLetter: {
        color: '#4317C6',
        fontSize: 16,
        fontFamily: 'Space Grotesk',
        fontWeight: '400',
    },
    optionLetterActive: {
        color: '#D7CFFF',
    },
    optionText: {
        flex: 1,
        paddingLeft: 16,
        color: '#1C1A24',
        fontSize: 16,
        fontFamily: 'Lexend',
        fontWeight: '400',
    },
    optionTextActive: {
        color: '#4317C6',
        fontWeight: '700',
    },
    topNav: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        height: 80,
        paddingTop: 30,
        paddingHorizontal: 24,
        backgroundColor: 'rgba(253, 248, 255, 0.7)',
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(201, 196, 216, 0.3)',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        zIndex: 10,
    },
    logoContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    logoText: {
        color: '#4317C6',
        fontSize: 24,
        fontFamily: 'Space Grotesk',
        fontWeight: '700',
    },
    timerBadge: {
        paddingHorizontal: 16,
        paddingVertical: 6,
        backgroundColor: '#F1ECF9',
        borderRadius: 9999,
        borderWidth: 1,
        borderColor: 'rgba(201, 196, 216, 0.3)',
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    timerText: {
        color: '#4317C6',
        fontSize: 16,
        fontFamily: 'Lexend',
    },
    footer: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        padding: 24,
        backgroundColor: 'rgba(253, 248, 255, 0.8)',
        borderTopWidth: 1,
        borderTopColor: 'rgba(201, 196, 216, 0.3)',
        flexDirection: 'row',
        gap: 16,
        zIndex: 10,
    },
    skipButton: {
        flex: 1,
        height: 56,
        backgroundColor: '#EBE6F3',
        borderRadius: 9999,
        justifyContent: 'center',
        alignItems: 'center',
    },
    skipText: {
        color: '#484555',
        fontSize: 16,
        fontFamily: 'Lexend',
    },
    nextButton: {
        flex: 2,
        height: 56,
        borderRadius: 9999,
        overflow: 'hidden',
    },
    nextButtonGradient: {
        flex: 1,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 8,
    },
    nextText: {
        color: 'white',
        fontSize: 16,
        fontFamily: 'Lexend',
    }
});
