import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FDF8FF',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 8,
    backgroundColor: 'transparent',
  },
  logoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  logoText: {
    fontSize: 20,
    fontWeight: '700',
    color: '#9174FF',
  },
  profilePic: {
    width: 36,
    height: 36,
    borderRadius: 18,
  },
  scrollContent: {
    paddingBottom: 160, 
  },
  titleContainer: {
    paddingHorizontal: 24,
    paddingVertical: 16,
  },
  title: {
    fontSize: 28,
    fontWeight: '700',
    color: '#1C1A24',
  },
  subtitle: {
    fontSize: 14,
    color: '#484555',
    marginTop: 4,
  },
  statsContainer: {
    flexDirection: 'row',
    paddingHorizontal: 24,
    gap: 16,
    marginBottom: 24,
  },
  statsCard: {
    flex: 1,
    backgroundColor: 'rgba(241, 236, 249, 0.5)',
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(196, 181, 253, 0.3)',
  },
  statsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 16,
  },
  statsIconBg: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#F1ECF9',
    justifyContent: 'center',
    alignItems: 'center',
  },
  statsCardTitle: {
    fontSize: 13,
    color: '#484555',
    lineHeight: 18,
  },
  statsValueRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
  },
  statsValue: {
    fontSize: 28,
    fontWeight: '600',
    color: '#1C1A24',
  },
  statsSubtitle: {
    fontSize: 11,
    color: '#4317C6',
    textAlign: 'right',
  },
  progressBarBg: {
    width: 40,
    height: 6,
    backgroundColor: '#E5DEFF',
    borderRadius: 3,
    marginBottom: 6,
  },
  progressBarFill: {
    height: '100%',
    borderRadius: 3,
  },
  searchContainer: {
    paddingHorizontal: 24,
    gap: 16,
    marginBottom: 24,
  },
  searchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FDF8FF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E5DEFF',
    paddingHorizontal: 16,
    height: 48,
  },
  searchIcon: {
    marginRight: 10,
  },
  searchInput: {
    flex: 1,
    fontSize: 15,
    color: '#1C1A24',
  },
  filterScroll: {
    gap: 12,
    paddingBottom: 4,
  },
  filterChip: {
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E5DEFF',
    backgroundColor: '#FFF',
    marginRight: 10,
  },
  filterChipActive: {
    backgroundColor: '#4317C6',
    borderColor: '#4317C6',
  },
  filterChipText: {
    fontSize: 14,
    color: '#484555',
  },
  filterChipTextActive: {
    color: '#FFF',
    fontWeight: '500',
  },
  historyList: {
    paddingHorizontal: 24,
    gap: 16,
    marginBottom: 24,
  },
  historyItem: {
    flexDirection: 'row',
    backgroundColor: 'rgba(241, 236, 249, 0.4)',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#F1ECF9',
    padding: 12,
    gap: 16,
  },
  thumbnailContainer: {
    width: 100,
    height: 100,
    borderRadius: 16,
    overflow: 'hidden',
    position: 'relative',
  },
  thumbnail: {
    width: '100%',
    height: '100%',
  },
  typeTag: {
    position: 'absolute',
    top: 8,
    left: 8,
    backgroundColor: 'rgba(0,0,0,0.4)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  typeTagText: {
    color: '#FFF',
    fontSize: 9,
    fontWeight: '700',
  },
  historyContent: {
    flex: 1,
    justifyContent: 'space-between',
  },
  historyContentTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  statusContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 4,
  },
  historyStatus: {
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 18,
  },
  historyTime: {
    fontSize: 10,
    
    color: '#484555',
    textAlign: 'right',
  },
  historyText: {
    fontSize: 15,
    fontWeight: '500',
    color: '#4317C6',
    lineHeight: 20,
    marginVertical: 4,
  },
  historyActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  actionBtn: {
    width: 28,
    height: 28,
    justifyContent: 'center',
    alignItems: 'center',
  },
  actionBtnActive: {
    backgroundColor: '#E5DEFF',
    borderRadius: 8,
  },
  goBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#4317C6',
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadMoreContainer: {
    marginHorizontal: 24,
    padding: 24,
    borderRadius: 24,
    borderWidth: 1.5,
    borderColor: '#E5DEFF',
    borderStyle: 'dashed',
    alignItems: 'center',
    gap: 12,
  },
  loadMoreIconBg: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#F1ECF9',
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadMoreText: {
    fontSize: 14,
    color: '#484555',
    textAlign: 'center',
    lineHeight: 20,
  },
  loadMoreBtn: {
    backgroundColor: '#9174FF',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 20,
    marginTop: 8,
  },
  loadMoreBtnText: {
    color: '#FFF',
    fontSize: 14,
    fontWeight: '600',
  },
  fabContainer: {
    position: 'absolute',
    bottom: 100,
    right: 24,
    zIndex: 20,
  },
  fab: {
    width: 60,
    height: 60,
    borderRadius: 30,
    shadowColor: '#5D3FDF',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
  },
  fabGradient: {
    flex: 1,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
});

export default styles;
