import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#FDF8FF',
    },
    header: {
        height: 56,
        paddingHorizontal: 24,
        paddingTop: 0,
        backgroundColor: '#FDF8FF',
        borderBottomWidth: 1,
        borderBottomColor: '#C9C4D8',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    logoText: {
        color: '#4317C6',
        fontSize: 24,
        fontFamily: 'Space Grotesk',
        fontWeight: '700',
    },
    profileIcon: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#EBE6F3',
        justifyContent: 'center',
        alignItems: 'center',
    },
    scrollView: {
        flex: 1,
    },
    content: {
        paddingHorizontal: 24,
        paddingVertical: 48,
        alignItems: 'center',
    },
    card: {
        width: '100%',
        maxWidth: 448,
        padding: 32,
        backgroundColor: '#F7F1FF',
        borderRadius: 20,
        borderWidth: 1,
        borderColor: '#C9C4D8',
        shadowColor: 'rgba(91, 60, 221, 0.1)',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 1,
        shadowRadius: 20,
        elevation: 5,
    },
    topIconSection: {
        alignItems: 'center',
        marginBottom: 32,
    },
    iconBox: {
        width: 64,
        height: 64,
        backgroundColor: '#5B3CDD',
        borderRadius: 16,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: 'rgba(0, 0, 0, 0.1)',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 1,
        shadowRadius: 6,
        elevation: 4,
    },
    cardTitle: {
        fontSize: 24,
        fontFamily: 'Space Grotesk',
        fontWeight: '600',
        color: '#1C1A24',
        textAlign: 'center',
        marginTop: 16,
    },
    cardSubtitle: {
        fontSize: 16,
        fontFamily: 'Lexend',
        color: '#484555',
        textAlign: 'center',
        marginTop: 8,
        lineHeight: 24,
    },
    form: {
        width: '100%',
        gap: 24,
    },
    inputGroup: {
        width: '100%',
    },
    label: {
        fontSize: 14,
        fontFamily: 'Lexend',
        fontWeight: '600',
        color: '#484555',
        marginBottom: 6,
    },
    inputWrapper: {
        height: 56,
        backgroundColor: 'white',
        borderRadius: 16,
        borderWidth: 2,
        borderColor: '#C9C4D8',
        paddingHorizontal: 16,
        justifyContent: 'center',
    },
    input: {
        fontSize: 16,
        fontFamily: 'Lexend',
        color: '#1C1A24',
    },
    agreementSection: {
        flexDirection: 'row',
        gap: 12,
        paddingVertical: 4,
    },
    checkbox: {
        width: 20,
        height: 20,
        borderRadius: 6,
        borderWidth: 1,
        borderColor: '#C9C4D8',
        backgroundColor: 'white',
    },
    agreementText: {
        fontSize: 14,
        fontFamily: 'Lexend',
        fontWeight: '600',
        color: '#484555',
        lineHeight: 20,
        flex: 1,
    },
    linkText: {
        color: '#4317C6',
    },
    signUpButton: {
        height: 56,
        backgroundColor: '#4317C6',
        borderRadius: 16,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 8,
        marginTop: 8,
    },
    signUpButtonText: {
        color: 'white',
        fontSize: 18,
        fontFamily: 'Lexend',
        fontWeight: '600',
    },
    footerSection: {
        marginTop: 24,
        paddingTop: 24,
        borderTopWidth: 1,
        borderTopColor: '#C9C4D8',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 4,
    },
    footerText: {
        fontSize: 16,
        fontFamily: 'Lexend',
        color: '#484555',
    },
    footerLink: {
        fontSize: 16,
        fontFamily: 'Lexend',
        fontWeight: '700',
        color: '#4317C6',
        paddingVertical: 8,
    }
});
